Fix AttributeError due to empty list
An empty list provided by the API resulted in the following error
when fetching locations:

File "/workspace/fetch.py", line 45, in fetch_set_of_locations

vehicles = list(r_json.keys())
                ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'

This commit fixes this error.